export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_ERROR="LOGIN_ERROR";
export const OTP_VERIFICATION="OTP_VERIFICATION";
export const PAGELOADERTRUE="PAGELOADERTRUE";
export const PAGELOADERFALSE="PAGELOADERFALSE";

export const PROFILEVERIFICATION="PROFILEVERIFICATION";
export const SETPROFILEDATA="SETPROFILEDATA";